### ISSUE TITLE
Server not working properly

### ISSUE THREAD

**Issue by heliocarbex** [hangxingliu/vscode-coding-tracker-server#15]
Hi friend,

I'm getting the following error(I tried to change the port number several times):

```
[Launch]: Local server launching...
16:19:29 [34mDebug mode be turned on![39m

[Error]: events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3001
    at Server.setupListenHandle [as _listen2] (net.js:1330:14)
    at listenInCluster (net.js:1378:12)
    at doListen (net.js:1491:7)
    at process._tickCallback (internal/process/next_tick.js:174:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1357:8)
    at process._tickCallback (internal/process/next_tick.js:174:19)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)

[Error]: local server exit with code 1!(have you launch another local sever?)
[Exit] exit code: 1
[Launch]: launching a new tracking server because detected old server exited!
[Launch]: Local server launching...
16:19:31 [34mDebug mode be turned on![39m

[Error]: events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3001
    at Server.setupListenHandle [as _listen2] (net.js:1330:14)
    at listenInCluster (net.js:1378:12)
    at doListen (net.js:1491:7)
    at process._tickCallback (internal/process/next_tick.js:174:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1357:8)
    at process._tickCallback (internal/process/next_tick.js:174:19)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)

[Error]: local server exit with code 1!(have you launch another local sever?)
[Exit] exit code: 1
```

**Comment by hangxingliu** [comment]
I can not reproduce it in my Windows 7 VM. I will update this reposiroty in the next days. And I will pay attention to this issue together.

**Comment by frandemona** [comment]
To us this happened when the port was already in use
